WaitForLevel with Timeout, Add Signed Scoreboard
OSVVM/OSVVM pull request #62
Opened 2021-07-29 14:55 UTC by klangthomas

Came across an issue while writing a test for a FIFO. Testbench blocks because the FIFO is empty and I wait for a data available level. 

Signed Scoreboard is implicitly available in Scoreboard_slv but we dont have to type cast ;) 

Sorry for just pushing into the main repo and not going the official way by creating an issue and else. Just clicked then wrong buttons. Still maybe valuable to others.

2024-05-16 19:59 UTC, Paebbels requested changes

2024-05-16 19:59 UTC, Paebbels commented on ScoreboardPkg_signed.vhd
> +--    Instance of Generic Package ScoreboardGenericPkg for integer
Please update the file header accordingly.

2024-05-16 19:59 UTC, Paebbels commented on TbUtilPkg.vhd
`TbUtilPkg.vhd` is overwritten by an older version (4 years old) of the file.

2024-05-17 05:10 UTC, klangthomas commented on ScoreboardPkg_signed.vhd
> +--    Instance of Generic Package ScoreboardGenericPkg for integer
done

2024-05-17 06:03 UTC, klangthomas commented on ScoreboardPkg_signed.vhd
> +--    Instance of Generic Package ScoreboardGenericPkg for integer
https://github.com/OSVVM/OSVVM/pull/62/commits/59abe63673861ed3788dbc24bf7681f54f533822

2024-05-17 18:19 UTC, JimLewis commented on TbUtilPkg.vhd
It looks like if I merge this it will remove the newer functionality from TbUtilPkg.vhd.   How does this get handled?

2024-05-17 19:33 UTC, Paebbels commented on TbUtilPkg.vhd
@klangthomas needs to either rebase his branch onto the latest main branch or merge the latest main branch into his branch. His modifications are 4 years old, and the proposed branch needs to be updated to the latest OSVVM release.

2024-05-22 10:43 UTC, klangthomas commented on TbUtilPkg.vhd
I messed up, sorry. Will fix that maybe today. As I will no longer have access to this account by friday, I hope can manage this to merge correctly.

2024-05-22 11:01 UTC, klangthomas commented
Messed up my commits here. Sorry about that!

2024-05-22 17:04 UTC, JimLewis commented
@Paebbels   Looks good to me.   Concur?

2024-05-22 20:37 UTC, Paebbels commented on TbUtilPkg.vhd
> +  procedure WaitForLevelTimeout ( signal A : in std_logic ; constant TimeOut : time; variable TimeOutReached : out boolean ; constant Polarity : std_logic := '1') is
I wouldn't call the parameter `polarity`, because an `std_logic` is not just `0` and `1`. Especially as it checks for not `0` or not `1`, which are 8 other values. The procedure is called `WaitForLevel`, so we should hand over the expected *level*. The existing `WaitForLevel` has already such a parameter.

I would prefer an overload with an additional `timeout` and `timeoutReached` parameter. `WaitForBarrier` is also overloaded.

2024-06-09 19:34 UTC, merged

2024-06-11 00:54 UTC, JimLewis commented
I have updated your WaitForLevelTimeout as follows:
```vhdl
  procedure WaitForLevel ( signal A : in boolean;   constant TimeOut : time);
  procedure WaitForLevel ( signal A : in std_logic; constant TimeOut : time; constant Polarity : std_logic := '1');

  procedure WaitForLevel ( signal A : in boolean;   constant TimeOut : time; variable TimeOutReached : out boolean);
  procedure WaitForLevel ( signal A : in std_logic; constant TimeOut : time; variable TimeOutReached : out boolean; constant Polarity : std_logic := '1');
  alias WaitForLevelTimeOut is WaitForLevel [boolean, time, boolean] ;
  alias WaitForLevelTimeOut is WaitForLevel [std_logic, time, boolean, std_logic] ;
```

The aliases make it so your original naming will still work.